# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b652d9ac9d1b1fc6bfabca0646c1974a9641a2b943a154474339382fdf921d6a9060d4f9840342b010878d61bd4d6f4ebcdb4242b895b5b031710ca4ff6091a
  twilio_key: xxxxxxxxxx

test:
  secret_key_base: 9fe031374485b3581af1aba39fd714018aae02a21b18a1fc85f53a6a46c86862d4c0c9a26ccf2f008aec1097da72d9f95f258598519b293fb0767985943e267c
  twilio_key: xxxxxxxxxx

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  twilio_key: <%= ENV["TWILIO_KEY"] %>